### ISSUE TITLE
Slack tr link doesn't work

### ISSUE THREAD

**Issue by halilatilla** [reactjs/tr.react.dev#400]
### [Slack #tr](https://rt-slack-invite.herokuapp.com/)
![Screenshot 2023-04-25 at 09 01 19](https://user-images.githubusercontent.com/27916419/234187594-25eb85e9-449c-493e-9be2-a7990904be4c.png)

**Comment by alioguzhan** [comment]
Merhaba, Discussions kismini actim repoda. Cogu kisi slack kullanmiyor. Orayi kullanabiliriz. Ama yine de buraya birakiyorum linki:

https://react-translations.slack.com/archives/CG5KFSDJ4


ben mumkun oldugunca online olmaya calisacagim slack'te.

**Comment by halilatilla** [comment]
Tamamdır, `Discussions` üzerinden de ilerleyebiliriz :)
