### ISSUE TITLE
Site tr.react.dev olması gerekmiyor mu?

### ISSUE THREAD

**Issue by Baturax** [reactjs/tr.react.dev#520]
Yeni React site react.dev oldu ama bu hala eski .org olana gönderiyor. Bunu tr.react.dev olarak yapmak gerekmiyor mu?

**Comment by yunusemredilber** [comment]
Selam. Yeni çeviriler tamamlandıktan yada belirli bir olgunluğa ulaştıktan sonra biz de geçişi yapmış oluruz.

**Comment by alioguzhan** [comment]
Ya aslinda ben onun PR'ini actim 2 ay once. Merge de oldu: https://github.com/reactjs/react.dev/pull/6449

Ama Vercel tarafinda subdomain ayarinin da yapilmasi gerekiyor. Bi daha sordum. Bakalim ne diyecekler.

**Comment by alioguzhan** [comment]
Taze geldi: https://tr.react.dev/
