### ISSUE TITLE
`memo` isn't stopping re-rendering in React when switching between tabs?

### ISSUE THREAD

**Issue by ishandutta2007** [reactjs/tr.react.dev#526]
I am using `memo` both on outer component as well as on each of the tab components.

Here is my `CommonContainer.tsx`:

```
import { Card, Divider, Grid, Spinner, Tabs, Text } from '@geist-ui/core'
import { memo, useCallback, useState } from 'react'
function CommonContainer(props: Props) {
  return (
    <Card width="100%">
      <Card.Content>
        <Tabs value="p1">
            <Tabs.Item label="P2" value="p2">
              <div >
                <P2QueryTab meta={props.metaList[0]} question={props.question}/>
              </div>
            </Tabs.Item>
            <Tabs.Item label="P1" value="p1">
              <div >
                <P1QueryTab meta={props.metaList[0]} question={props.question}/>
              </div>
            </Tabs.Item>
        </Tabs>
      </Card.Content>
    </Card>
  )
}

export default memo(CommonContainer)

```

Here is my `P2QueryTab.tsx`:

```
import { memo, useEffect, useCallback, useState } from 'react'
import Browser from 'webextension-polyfill'
function P2QueryTab(props: Props) {
  const [answer, setAnswer] = useState<Answer | null>(null)


  useEffect(() => {
    const port = Browser.runtime.connect()
    const listener = (msg: any) => {
      if (msg.text) {
        setAnswer(msg)
      }
    }
    port.onMessage.addListener(listener)
//This postMessage in turn will call external API to get data 
    port.postMessage({ question: props.meta + ' ' + props.question, displayTab: "Insights" })
    return () => {
      port.onMessage.removeListener(listener)
      port.disconnect()
    }
  }, [props.question])


  if (answer) {
    return (
      <div id="answer" dir="auto">
        {answer.text}
      </div>
    )
  }

  return <p className="animate-pulse">Waiting for P2...</p>
}

export default memo(P2QueryTab)
```

Here is my `P1QueryTab.tsx`:
```
import { memo, useEffect, useCallback, useState } from 'react'
import Browser from 'webextension-polyfill'
function P1QueryTab(props: Props) {
  const [answer, setAnswer] = useState<Answer | null>(null)

  useEffect(() => {
    const port = Browser.runtime.connect()
    const listener = (msg: any) => {
      if (msg.text) {
        setAnswer(msg)
      }
    }
    port.onMessage.addListener(listener)
//This postMessage in turn will call external API to get data 
    port.postMessage({
      question: props.meta + ' ' + props.question
    })
    return () => {
      port.onMessage.removeListener(listener)
      port.disconnect()
    }
  }, [props.question])

  if (answer) {
    return (
      <div id="answer" dir="auto">
        {answer.text}
      </div>
    )
  }

  return <p className="animate-pulse">Waiting for P1...</p>
}

export default memo(P1QueryTab)

```

I have gone through [this](https://stackoverflow.com/questions/59798377/avoid-re-rendering-in-react-when-switching-between-tabs) and [this](https://stackoverflow.com/questions/58996194/react-memo-why-is-my-equality-function-not-being-called/58997083#58997083) and [this](https://stackoverflow.com/questions/69873359/react-memo-not-calling-comparison-function) and [this](https://stackoverflow.com/questions/62868907/how-to-use-reacts-built-in-react-memo-comparison-function) but still my problem is unsolved.

- most people facing this issue is due to key but I don't have key, I have only 2 props: `meta` and `question` which are guaranteed to be same as i visited a tab las time around.
- [this](https://stackoverflow.com/a/59947407/865220) answer doesn't rely on `memo` and does the css trick explicitly himself. Not sure his `Typography` component uses any memorisation at all. But before going that route I need to understand why don't `memo` work in my case, why isn't the custom comparator even getting called.
- Some blamed geist-ui tabs so I switched to [react-tabs](https://www.npmjs.com/package/react-tabs), but result is still the same.

**Comment by alioguzhan** [comment]
Hi @ishandutta2007,

I think you confused the repositories :) This is `tr.react.dev`. Turkish translation of the official React website. Closing this.

**Comment by ishandutta2007** [comment]
@alioguzhan  can you help me transfer it to the correct one? I would be great if you can tag the correct repo.

**Comment by alioguzhan** [comment]
@ishandutta2007 I don't think any official React repository is the right place to ask this kind of question. You can ask your question on the StackOverflow or Discord channels.

**Comment by ishandutta2007** [comment]
@alioguzhan which discord channel ?

**Comment by alioguzhan** [comment]
Please refer to this: https://react.dev/community

**Comment by ishandutta2007** [comment]
@alioguzhan I thought you were talking of some discord channel.  Anyways thank a lot.
